config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :machines

  # Defines the root path route ("/")
  root "machines#index"

  namespace :api do
    namespace :v1 do
      resources :machines
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/machine.rb
class Machine < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    has_one_attached :image
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/machines_controller.rb
module Api
    module V1
        class MachinesController < ApplicationController
 
            skip_before_action :verify_authenticity_token

            def index
                render json: Machine.all
            end
        
            def show
                render json: Machine.find(params[:id])
            end
            
            def create
                @machine = Machine.new(machine_params)
                if @machine.save
                    render json: @machine.reload, status: 200
                else
                    render json: {errors: @machine.errors }, status: 400
                end
            end
            
            def update
                @machine = Machine.find(params[:id])
                if @machine
                    @machine.update(machine_params)
                    render json: 'Machine updated successfully', status: 200
                else
                    render error: 'unable to create Machine' , status: 400
                end
            end
            
            def destroy
                @machine = Machine.find(params[:id])
                @machine.destroy
                    render json: "Machine deleted succesfully"
            end

            private
            def machine_params
            params.require(:machine).permit(:name, :description)
            end

        end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/machines_controller.rb
class MachinesController < ApplicationController
    

    def index  
       @machines = Machine.all 
    end

    def show
        @machine = Machine.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path 
    end
    
    def new
        @machine = Machine.new
    end

    def create
        @machine = Machine.new(machine_params)
        if @machine.save
            redirect_to @machine
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @machine = Machine.find(params[:id])
    end

    def update
        @machine = Machine.find(params[:id])
        if @machine.update(machine_params)
            redirect_to @machine
        else 
            render :edit, status: :unprocessable_entity
        end
        
    end

    def destroy
        @machine = Machine.find(params[:id])
        @machine.destroy
        redirect_to root_path
    end



    private

    def machine_params
        params.require(:machine).permit(:name, :description, :image)
    end 


end

app/helpers/api/machine_helper.rb
module Api::MachineHelper
end

app/helpers/api/your_controller_name_helper.rb
module Api::YourControllerNameHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projet</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href='style.css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
    /* Additional styling for the animated title */
    .animated-title {
      animation: fadeAnimation 3s ease-in-out infinite alternate; /* New animation */
      font-family: 'Cursive'; /* Change the font family */
      color: #88C6FF; /* Change the text color */
      font-style: italic; /* Italic style */
      font-weight: bold; /* Bold style */
    }

    @keyframes fadeAnimation {
      0%, 100% {
        opacity: 1;
      }
      50% {
        opacity: 0.5;
      }
    }

    /* Add margin to the right for Log out and Profile links */
    .profile-link,
    .logout-link {
      margin-right: 20px; /* Increased margin for more spacing */
    }
  </style>
</head>
<body>
  <div class="bg-center bg-cover w-full h-screen" style="background-image: url('https://i.pinimg.com/564x/78/46/59/78465959c9d1d8fc5d54aa4ab72fbf9c.jpg')">
    <p class="notice text-white"><%= notice %></p> 
    <p class="alert text-white"><%= alert %></p>
    <div class="flex justify-between pt-2 pl-4"> <!-- Changed flex layout and added padding -->
      <h1 class="animated-title w-fit m-auto text-4xl" ><strong><em>Leanios Machine Hub</em></strong></h1>


      <% if user_signed_in? %>
        <div class="flex items-center ">
          <%= link_to "Profile", edit_user_registration_path, class: "profile-link bg-zinc-700 hover:bg-blue-600 rounded-r-lg rounded-l-lg text-white font-semibold px-4 py-2" %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "logout-link bg-zinc-700 hover:bg-blue-600 rounded-r-lg rounded-l-lg text-white font-semibold px-4 py-2" %>
        </div>
      <% else %>
        <div class="flex space-x-2">
          <%= link_to "Login", new_user_session_path, class: "text-white" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "text-white" %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/machines/_form.html.erb
<%= form_with model: @machine, multipart: true do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="mb-4 mt-5 ml-5 mr-5">
    <div>
      <%= form.label :name, class: "text-gray-300" %>
    </div>
    <div>
      <%= form.text_field :name, class: "form-input w-full p-2 rounded-md bg-gray-800 text-gray-300" %>
    </div>
  </div>

  <div class="mb-4 mt-5 ml-5 mr-5">
    <div>
      <%= form.label :serial_number, class: "text-gray-300" %>
    </div>
    <div>
      <%= form.text_field :serial_number, class: "form-input w-full  p-2 rounded-md bg-gray-800 text-gray-300" %>
    </div>
  </div>

  <div class="mt-5 ml-5 mr-5">
    <div>
      <%= form.label :description, class: "text-gray-300" %>
    </div>
    <div>
      <%= form.text_area :description, class: "form-input w-full p-2 rounded-md bg-gray-800 text-gray-300" %>
    </div>
  </div>

  <div class="mb-10 ml-5 mr-5">
    <div>
      <%= form.label :image, class: "text-gray-300" %>
    </div>
    <div>
      <%= form.file_field :image, class: "form-input rounded-lg gray-input text-gray-300" %>
    </div>
  </div>

  <div class="mb-4 flex justify-between ml-48">
    <%= link_to "Back", :back, class: "bg-cyan-700 hover:bg-red-600 rounded-lg text-white font-semibold px-4 py-2 mr-2" %>
    <%= form.button class: "bg-cyan-500 hover:bg-blue-600 text-white font-bold py-2 px-3 rounded-lg" %>
  </div>

<% end %>

app/views/machines/edit.html.erb
<style>
  @media (max-width: 768px) {
    .grid-cols-2 {
      grid-template-columns: 1fr;
      margin-top: 20px; /* Add margin to move the grids downward */
    }
  }

  body {
    margin: 0;
    padding: 0;
    background: url('https://i.pinimg.com/564x/78/46/59/78465959c9d1d8fc5d54aa4ab72fbf9c.jpg') no-repeat center center fixed;
    background-size: cover;
  }

  @media (max-width: 480px) {
    .h-screen {
      height: auto;
      min-height: 100vh;
    }
    .grid-cols-2 {
      grid-template-columns: 1fr;
      margin-top: 20px; /* Add margin to move the grids downward */
    }
    .col-span-1 {
      text-align: center;
    }
  }
</style>

<div class="flex justify-center items-center h-screen">
  <div class="grid grid-cols-2 gap-7 mt-0 mb-20 w-3/4 lg:w-2/3 xl:w-1/2">

    <div class="col-span-1">
      <p class="text-5xl font-bold mt-6 text-white">Edit</p>
      <p class="text-5xl font-bold mt-2 text-white">This Machine</p>
      <hr class="mt-10 w-20 border-t-4 border-purple-300">
      <p class="text-1xl mt-6 font-bold text-white">Do you want to modify this machine?</p>
      <p class="text-1xl mt-2 font-bold text-white">Let's do it!</p>
    </div>

    <div class="col-span-1 flex flex-col justify-center items-center bg-gray-600 bg-opacity-50 text-white rounded-lg overflow-hidden">
      <h1 class="text-4xl font-bold mt-2 mb-4">Edit</h1>
      <%= render partial: "form", locals: {machine: @machine} %>
    </div>
    
  </div>
</div>

app/views/machines/index.html.erb
<style>
  body {
    margin: 0;
    padding: 0;
    background: url('https://i.pinimg.com/564x/78/46/59/78465959c9d1d8fc5d54aa4ab72fbf9c.jpg') no-repeat center center fixed;
    background-size: cover;
  }

  .grid-item {
    transition: all 0.3s ease-in-out;
  }

  .grid-item:hover {
    transform: scale(1.1); /* You can adjust the scale factor as needed */
  }
</style>

<div class="mt-7 mb-10 mx-4 md:mx-10 ">
  <%= link_to "New machine", new_machine_path, class: "bg-zinc-700 hover:bg-blue-600 rounded-lg text-white font-semibold px-4 py-2" %>
</div>

<div class="mx-4 md:mx-20">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mt-4 md:mt-7 ">
    <% @machines.each do |machine| %>
      <div class="bg-gray-100 bg-opacity-30 rounded-lg flex flex-col items-center justify-center p-7 grid-item">
        <p class="w-fit m-auto"><%= image_tag(machine.image, style: "max-width: 100%; height: auto;") if machine.image.attached? %></p><br>
        <h2 class="bg-zinc-600 hover:bg-blue-600 rounded-lg text-white px-4 py-2 font-semibold text-center"><%= link_to machine.name, machine %></h2>
        <%# <%= machine.description %>
      </div>
    <% end %>
  </div>
</div>

<script>
  const gridItems = document.querySelectorAll('.grid-item');
  gridItems.forEach(item => {
    item.addEventListener('mouseover', () => {
      item.style.transform = 'scale(1.1)';
    });

    item.addEventListener('mouseout', () => {
      item.style.transform = 'scale(1)';
    });
  });
</script>

app/views/machines/new.html.erb
<style>
  body {
    margin: 0;
    padding: 0;
    background: url('https://i.pinimg.com/564x/78/46/59/78465959c9d1d8fc5d54aa4ab72fbf9c.jpg') no-repeat center center fixed;
    background-size: cover;
  }

  .grid-item {
    transition: all 0.3s ease-in-out;
  }

  .grid-item:hover {
    transform: scale(1.1); /* You can adjust the scale factor as needed */
  }
</style>

<div class="flex justify-center items-center min-h-screen">
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-7 mt-0 mb-20 w-full lg:w-2/3 xl:w-1/2">
    <div class="col-span-1">
      <p class="text-3xl lg:text-5xl font-bold text-white">Create New Machine</p>
      <hr class="mt-3 lg:mt-6 w-16 lg:w-20 border-t-2 lg:border-t-4 border-purple-300">
      <p class="text-base lg:text-xl mt-3 lg:mt-6 font-bold text-white">Do you want to create a new machine and track its data?</p>
      <p class="text-base lg:text-xl mt-3 lg:mt-6 font-bold text-white">Let's create it!</p>
    </div>
    <div class="col-span-1 flex flex-col justify-center bg-gray-600 bg-opacity-50 text-white rounded-lg overflow-hidden">
      <h1 class="text-2xl lg:text-4xl font-bold mb-2 lg:mb-4">New Machine</h1>
      <%= render partial: "form", locals: {machine: @machine} %>
    </div>
  </div>
</div>

app/views/machines/show.html.erb
<style>
  body {
    margin: 0;
    padding: 0;
    background: url('https://i.pinimg.com/564x/78/46/59/78465959c9d1d8fc5d54aa4ab72fbf9c.jpg') no-repeat center center fixed;
    background-size: cover;
  }

  .grid-item {
    transition: all 0.3s ease-in-out;
  }

  .grid-item:hover {
    transform: scale(1.1); /* You can adjust the scale factor as needed */
  }
</style>

<div class="flex ml-4">
  <%= link_to "Back", machines_path ,class: "bg-zinc-700 hover:bg-blue-600 rounded-lg text-white font-semibold px-4 py-2 mr-2"%>
</div>
<div class="flex justify-center items-center bg-[url('/home/hp/Téléchargements/fond.png')] bg-center bg-no-repeat bg-cover min-h-screen">
  <div class="text-center p-4 md:p-8">
    <h1 class="text-4xl md:text-4xl font-bold text-white mb-2"><%= @machine.name %></h1>
    <p class="w-fit m-auto justify-center items-center "><%= image_tag(@machine.image, style:"max-width:300px;height:auto;") if @machine.image.attached? %></p><br>
    <p class="mb-4 text-white"><%= @machine.description %></p>

    <div class="flex justify-center items-center flex-col md:flex-row gap-2">
      <%= button_to "Edit", edit_machine_path(@machine), method: :get, class: "bg-cyan-500 hover:bg-blue-600 rounded-lg text-white font-semibold px-4 py-2" %>
      <%= button_to "Delete", @machine, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "bg-cyan-700 hover:bg-red-600 text-white font-semibold px-4 py-2 rounded-lg" %>
    </div>
  </div>
</div>